### ISSUE TITLE
pip install fails with windows 10 python 3.7

### ISSUE THREAD

**Issue by jasonbrackman** [plasma-umass/scalene#222]
**Describe the bug**
Running pip install of scalene fails.  It attempts to download 1.3.6 (latest at this time) and will continue to fail and try earlier versions until it results in a final error at 1.3.4.

**To Reproduce**
0. Ensure you have python 3.7 installed
1. Open a cmd prompt
2. run the following: py -3.7 -m pip install -U --no-cache-dir scalene

**Expected behavior**
The pip install should complete without error.

**Actual Behavior**
U:\>py -3.7 -m pip install -U --no-cache-dir scalene
Collecting scalene
  Downloading scalene-1.3.6.tar.gz (6.9 MB)
     |████████████████████████████████| 6.9 MB 6.4 MB/s
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files\Python37\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\---\\AppData\\Local\\Temp\\pip-install-76c5d472\\scalene_775ff2f3f56a4cdcbd9d54aa1e0fb6ec\\setup.py'"'"'; __file__='"'"'C:\\Users\\---\\AppData\\Local\\Temp\\pip-install-76c5d472\\scalene_775ff2f3f56a4cdcbd9d54aa1e0fb6ec\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\---\AppData\Local\Temp\pip-pip-egg-info-5jj_5uyx'
         cwd: C:\Users\---\AppData\Local\Temp\pip-install-76c5d472\scalene_775ff2f3f56a4cdcbd9d54aa1e0fb6ec\
    Complete output (1 lines):
    Unexpected error: [WinError 2] The system cannot find the file specified
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/45/e9/fdc687bccd185d6309b8a1344c6aa957d11fdda594035a84f1d30b4c624d/scalene-1.3.6.tar.gz#sha256=7cd1782103bff74ecdecb835025a2a71a6bea52ea0046ed2104f89f53fc62990 (from https://pypi.org/simple/scalene/) (requires-python:>=3.7). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

.....

 Downloading scalene-1.3.4.1.tar.gz (3.5 MB)
     |████████████████████████████████| 3.5 MB 6.8 MB/s
Requirement already satisfied: rich>=9.2.10 in c:\program files\python37\lib\site-packages (from scalene) (10.3.0)
Requirement already satisfied: cloudpickle>=1.5.0 in c:\program files\python37\lib\site-packages (from scalene) (1.6.0)
Requirement already satisfied: nvidia-ml-py==11.450.51 in c:\program files\python37\lib\site-packages (from scalene) (11.450.51)
Requirement already satisfied: numpy in c:\users\---\appdata\roaming\python\python37\site-packages (from scalene) (1.19.5)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in c:\users\---\appdata\roaming\python\python37\site-packages (from rich>=9.2.10->scalene) (2.9.0)
Requirement already satisfied: typing-extensions<4.0.0,>=3.7.4 in c:\program files\python37\lib\site-packages (from rich>=9.2.10->scalene) (3.10.0.0)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in c:\program files\python37\lib\site-packages (from rich>=9.2.10->scalene) (0.9.1)
Requirement already satisfied: colorama<0.5.0,>=0.4.0 in c:\program files\python37\lib\site-packages (from rich>=9.2.10->scalene) (0.4.4)
Using legacy 'setup.py install' for scalene, since package 'wheel' is not installed.
Installing collected packages: scalene
    Running setup.py install for scalene ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files\Python37\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\---\\AppData\\Local\\Temp\\pip-install-76c5d472\\scalene_82e4920202fc417bb27123698dd98c5d\\setup.py'"'"'; __file__='"'"'C:\\Users\\---\\AppData\\Local\\Temp\\pip-install-76c5d472\\scalene_82e4920202fc417bb27123698dd98c5d\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\---\AppData\Local\Temp\pip-record-07h7ccl2\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Program Files\Python37\Include\scalene'
         cwd: C:\Users\---\AppData\Local\Temp\pip-install-76c5d472\scalene_82e4920202fc417bb27123698dd98c5d\
    Complete output (61 lines):
    WARNING: The wheel package is not available.
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\scalene
    copying scalene\adaptive.py -> build\lib.win-amd64-3.7\scalene
    copying scalene\leak_analysis.py -> build\lib.win-amd64-3.7\scalene
    copying scalene\profile.py -> build\lib.win-amd64-3.7\scalene
    copying scalene\replacement_exit.py -> build\lib.win-amd64-3.7\scalene
    copying scalene\replacement_fork.py -> build\lib.win-amd64-3.7\scalene
    copying scalene\replacement_lock.py -> build\lib.win-amd64-3.7\scalene
    copying scalene\replacement_mp_lock.py -> build\lib.win-amd64-3.7\scalene
    copying scalene\replacement_pjoin.py -> build\lib.win-amd64-3.7\scalene
    copying scalene\replacement_poll_selector.py -> build\lib.win-amd64-3.7\scalene
    copying scalene\replacement_thread_join.py -> build\lib.win-amd64-3.7\scalene
    copying scalene\runningstats.py -> build\lib.win-amd64-3.7\scalene
    copying scalene\scalene_arguments.py -> build\lib.win-amd64-3.7\scalene
    copying scalene\scalene_gpu.py -> build\lib.win-amd64-3.7\scalene
    copying scalene\scalene_magics.py -> build\lib.win-amd64-3.7\scalene
    copying scalene\scalene_output.py -> build\lib.win-amd64-3.7\scalene
    copying scalene\scalene_parseargs.py -> build\lib.win-amd64-3.7\scalene
    copying scalene\scalene_preload.py -> build\lib.win-amd64-3.7\scalene
    copying scalene\scalene_profiler.py -> build\lib.win-amd64-3.7\scalene
    copying scalene\scalene_signals.py -> build\lib.win-amd64-3.7\scalene
    copying scalene\scalene_statistics.py -> build\lib.win-amd64-3.7\scalene
    copying scalene\scalene_version.py -> build\lib.win-amd64-3.7\scalene
    copying scalene\sparkline.py -> build\lib.win-amd64-3.7\scalene
    copying scalene\syntaxline.py -> build\lib.win-amd64-3.7\scalene
    copying scalene\__init__.py -> build\lib.win-amd64-3.7\scalene
    copying scalene\__main__.py -> build\lib.win-amd64-3.7\scalene
    running egg_info
    writing scalene.egg-info\PKG-INFO
    writing dependency_links to scalene.egg-info\dependency_links.txt
    writing entry points to scalene.egg-info\entry_points.txt
    writing requirements to scalene.egg-info\requires.txt
    writing top-level names to scalene.egg-info\top_level.txt
    reading manifest file 'scalene.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'heaplayers-make.mk'
    adding license file 'LICENSE'
    writing manifest file 'scalene.egg-info\SOURCES.txt'
    copying scalene\README.md -> build\lib.win-amd64-3.7\scalene
    copying scalene\libscalene.dylib -> build\lib.win-amd64-3.7\scalene
    copying scalene\libscalene.so -> build\lib.win-amd64-3.7\scalene
    copying scalene\scalene-usage.txt -> build\lib.win-amd64-3.7\scalene
    running build_ext
    building 'get_line_atomic' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\src
    creating build\temp.win-amd64-3.7\Release\src\source
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I. -Ivendor/Heap-Layers -Ivendor/Heap-Layers/utility "-IC:\Program Files\Python37\include" "-IC:\Program Files\Python37\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.15.26726\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.15.26726\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tpsrc/source/get_line_atomic.cpp /Fobuild\temp.win-amd64-3.7\Release\src/source/get_line_atomic.obj -std=c++14
    cl : Command line warning D9002 : ignoring unknown option '-std=c++14'
    get_line_atomic.cpp
    c:\users\---\appdata\local\temp\pip-install-76c5d472\scalene_82e4920202fc417bb27123698dd98c5d\vendor\heap-layers\utility\ilog2.h(32): warning C4267: 'argument': conversion from 'size_t' to 'DWORD', possible loss of data
    c:\users\---\appdata\local\temp\pip-install-76c5d472\scalene_82e4920202fc417bb27123698dd98c5d\vendor\heap-layers\heaps\utility\exceptionheap.h(38): warning C4290: C++ exception specification ignored except to indicate a function is not __declspec(nothrow)
    c:\users\---\appdata\local\temp\pip-install-76c5d472\scalene_82e4920202fc417bb27123698dd98c5d\vendor\heap-layers\heaps\utility\exceptionheap.h(45): note: see reference to class template instantiation 'HL::ExceptionHeap<Super>' being compiled
    c:\users\---\appdata\local\temp\pip-install-76c5d472\scalene_82e4920202fc417bb27123698dd98c5d\vendor\heap-layers\heaps\utility\sysmallocheap.h(61): fatal error C1083: Cannot open include file: 'dlfcn.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Program Files\Python37\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\---\\AppData\\Local\\Temp\\pip-install-76c5d472\\scalene_82e4920202fc417bb27123698dd98c5d\\setup.py'"'"'; __file__='"'"'C:\\Users\\---\\AppData\\Local\\Temp\\pip-install-76c5d472\\scalene_82e4920202fc417bb27123698dd98c5d\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\---\AppData\Local\Temp\pip-record-07h7ccl2\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Program Files\Python37\Include\scalene' Check the logs for full command output.

**Desktop (please complete the following information):**
 - Windows 10
 - Python 3.7

**Comment by LangDaoAI** [comment]
win10 and python 3.9 same problem!

**Comment by LangDaoAI** [comment]
>pip install -U scalene
Collecting scalene
  Downloading scalene-1.3.6.tar.gz (6.9 MB)
     |████████████████████████████████| 6.9 MB 29 kB/s
    ERROR: Command errored out with exit status 1:
     command: 'd:\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\t00019588\\AppData\\Local\\Temp\\pip-install-_gjfj6gn\\scalene_023b998587a44d66ab1b913b7883b87c\\setup.py'"'"';
__file__='"'"'C:\\Users\\t00019588\\AppData\\Local\\Temp\\pip-install-_gjfj6gn\\scalene_023b998587a44d66ab1b913b7883b87c\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO
('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\t00019588\AppData\Local\Temp\pip-pip-egg-in
fo-axghco0v'
         cwd: C:\Users\t00019588\AppData\Local\Temp\pip-install-_gjfj6gn\scalene_023b998587a44d66ab1b913b7883b87c\
    Complete output (1 lines):
    Unexpected error: [WinError 2] 系统找不到指定的文件。
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/45/e9/fdc687bccd185d6309b8a1344c6aa957d11fdda594035a84f1d30b4c624d/scalene-1.3.6.tar.gz#sha256=7cd1782103bff74ecdecb835025a2a71a6bea52ea0046ed2104f89f53fc62990 (from https://
pypi.org/simple/scalene/) (requires-python:>=3.7). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading scalene-1.3.5.tar.gz (6.9 MB)
     |████████████████████████████████| 6.9 MB 29 kB/s
    ERROR: Command errored out with exit status 1:
     command: 'd:\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\t00019588\\AppData\\Local\\Temp\\pip-install-_gjfj6gn\\scalene_c45772261b7f46f89af3087cc68d2df6\\setup.py'"'"';
__file__='"'"'C:\\Users\\t00019588\\AppData\\Local\\Temp\\pip-install-_gjfj6gn\\scalene_c45772261b7f46f89af3087cc68d2df6\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO
('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\t00019588\AppData\Local\Temp\pip-pip-egg-in
fo-7qbjo1ol'
         cwd: C:\Users\t00019588\AppData\Local\Temp\pip-install-_gjfj6gn\scalene_c45772261b7f46f89af3087cc68d2df6\
    Complete output (1 lines):
    Unexpected error: [WinError 2] 系统找不到指定的文件。
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/e7/1d/1a562dad8e7b70447308cd14b0b9f950a83cc35957ff7a93416dc10a78da/scalene-1.3.5.tar.gz#sha256=e022e3ea8fc5935e9c86726747544f8186bfb241b2294613f29f8ba3c99a6000 (from https://
pypi.org/simple/scalene/) (requires-python:>=3.7). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading scalene-1.3.4.7.tar.gz (6.5 MB)
     |████████████████████████████████| 6.5 MB 29 kB/s
    ERROR: Command errored out with exit status 1:
     command: 'd:\python\python39\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\t00019588\\AppData\\Local\\Temp\\pip-install-_gjfj6gn\\scalene_b55d15a08ee4462788b00a9525aa3304\\setup.py'"'"';
__file__='"'"'C:\\Users\\t00019588\\AppData\\Local\\Temp\\pip-install-_gjfj6gn\\scalene_b55d15a08ee4462788b00a9525aa3304\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO
('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\t00019588\AppData\Local\Temp\pip-pip-egg-in
fo-ktqtj9eu'
         cwd: C:\Users\t00019588\AppData\Local\Temp\pip-install-_gjfj6gn\scalene_b55d15a08ee4462788b00a9525aa3304\
    Complete output (1 lines):
    Unexpected error: [WinError 2] 系统找不到指定的文件。
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/fa/88/c4765fb33e9e0cb62821086242bbda8daf6ed6a78a23f3c025aa7bd98e75/scalene-1.3.4.7.tar.gz#sha256=8cc204e584b2b9149de1f882ee58e09ceec8c35ee72052f661a65a9113dd9126 (from https:
//pypi.org/simple/scalene/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading scalene-1.3.4.6.tar.gz (6.5 MB)
     |██                              | 358 kB 34 kB/s eta 0:02:59
ERROR: Operation cancelled by user

**Comment by dgrinin** [comment]
win10 and python 3.8 same problem!

**Comment by samanemami** [comment]
I have the same problem.

- OS: Windows 10
- Python: 3.6.5
- Platform to install: pip
- Editor: VSCode

I am seeing that after almost one month nobody answered the issue!
Have someone found any solution?

**Comment by emeryberger** [comment]
This has hopefully been fixed with the new version (1.3.9). Please give it a shot!

**Comment by jasonbrackman** [comment]
Unfortunately it still fails.

This is the first of the cascading set of errors listed:

    Complete output (4 lines):
    WARNING: The wheel package is not available.
    running egg_info
    nmake vendor-deps
    error: command 'nmake' failed: No such file or directory

**Comment by emeryberger** [comment]
Got it: the problem is that it currently requires the Visual Studio tools to be installed. We expect to have this fixed with a new version  tomorrow. Thanks for your patience!

**Comment by jaltmayerpizzorno** [comment]
Please try again now... and reopen if it doesn't work. :)

**Comment by ywilke** [comment]
@jaltmayerpizzorno

Still have an issue with python 3.8 on windows 10 in my conda environment. 

`````
Collecting scalene
  Using cached scalene-1.3.16.tar.gz (2.8 MB)
  Preparing metadata (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\username\miniconda3\envs\my_project\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-0p3yg
juq\\scalene_184fb1a401944245a38c9d6678bbf637\\setup.py'"'"'; __file__='"'"'C:\\Users\\username\\AppData\\Local\\Temp\\pip-install-0p3ygjuq\\scalene_184fb1a401944245a38c9d6678bbf637\\setup.py
'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n
'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\username\AppData\Local\Temp\pip-pip-egg-info-7qstoskf'
       cwd: C:\Users\username\AppData\Local\Temp\pip-install-0p3ygjuq\scalene_184fb1a401944245a38c9d6678bbf637\
  Complete output (5 lines):
  running egg_info
  make vendor-deps
  C:\Users\username\AppData\Roaming\Python\Python38\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfie
d by a PEP 517 installer.
    warnings.warn(
  error: command 'make' failed: No such file or directory
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/e8/35/a125f8ecacfce3b9be9c712bd6d9bd514aed798857cc7330c89d2df7db58/scalene-1.3.16.tar.gz#sha256=3c2fb524b4c611773b147dc889e2d58
b48a543d3161ea576ccc0db778e9f5915 (from https://pypi.org/simple/scalene/) (requires-python:>=3.7). Command errored out with exit status 1: python setup.py egg_info Check the logs for full
 command output.
`````
