### ISSUE TITLE
libscalene.so included in scalene v1.1.1 requires more recent glibc when running on CentOS 7.8

### ISSUE THREAD

**Issue by boegel** [plasma-umass/scalene#77]
When trying `scalene` v1.1.1 (installed from source with `pip install .`, but I don't think that matters since `libscalene.so` is included in the source tarball), I'm getting this:

```
python3: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /.../lib/python3.6/site-packages/scalene/libscalene.so)
```

The issue here boils down to `libscalene.so` being compiled on an Linux OS that has a more recent glibc than is used in CentOS 7.8 (which is glibc 2.17).

Is there a specific reason why `libscalene.so` is packaged into the source tarball, as opposed to compiling it from source when scalene is being installed from source?

I'm happy to try and compile `libscalene.so` from source myself, but there doesn't seem to be any documentation available on that. I found [heaplayers-make.mk](https://github.com/emeryberger/scalene/blob/master/heaplayers-make.mk) which suggests that `clang++` is needed (is that a strict requirement, or would a sufficiently recent `g++` also work?), and that some source code from https://github.com/emeryberger/Heap-Layers is required as well.

**Comment by emeryberger** [comment]
Including the `.so` and `.dylib` files lets Scalene work even without a C/C++ development environment, so it seems to be the most expedient. You can rebuild them just by invoking `make` (and if you want to build with `g++`, you can say `make CXX=g++`).

**Comment by boegel** [comment]
Rebuilding using the source tarball from PyPI doesn't work currently, because it doesn't include `GNUmakefile`, `heaplayers-make.mk` and `libscalene.cpp`.

I can look into a pull request to fix that...

**Comment by boegel** [comment]
With the changes in #78, the necessary files to rebuild `libscalene.so` are included in the source tarball that you obtain via `python setup.py sdist`.

I'm still experiencing problems when trying to build `libscalene.so` with `g++` (v9.3.0) however:

```
$ make CXX=g++
git clone https://github.com/emeryberger/Heap-Layers
Cloning into 'Heap-Layers'...
g++ -std=c++17 -g -O3 -flto -DNDEBUG -fno-builtin-malloc -fvisibility=hidden -D'CUSTOM_PREFIX(x)=xx##x' -I/usr/include/nptl -fno-builtin-malloc -pipe -fPIC -I. -I./include -IHeap-Layers -IHeap-Layers/wrappers -IHeap-Layers/utility -D_REENTRANT=1 -shared libscalene.cpp Heap-Layers/wrappers/gnuwrapper.cpp -Bsymbolic -o libscalene.so -ldl -lpthread
libscalene.cpp:318:65: warning: always_inline function might not be inlinable [-Wattributes]                                                                                                                                                                                      
318 | extern "C" ATTRIBUTE_EXPORT __attribute__((always_inline)) void xxmalloc_unlock() {                                                                                                                                                                                           
|                                                                 ^~~~~~~~~~~~~~~                                                                                                                                                                                         
libscalene.cpp:314:65: warning: always_inline function might not be inlinable [-Wattributes]                                                                                                                                                                                      
314 | extern "C" ATTRIBUTE_EXPORT __attribute__((always_inline)) void xxmalloc_lock() {                                                                                                                                                                                             
|                                                                 ^~~~~~~~~~~~~                                                                                                                                                                                           
libscalene.cpp:310:67: warning: always_inline function might not be inlinable [-Wattributes]                                                                                                                                                                                      
310 | extern "C" ATTRIBUTE_EXPORT __attribute__((always_inline)) size_t xxmalloc_usable_size(void * ptr) {                                                                                                                                                                          
|                                                                   ^~~~~~~~~~~~~~~~~~~~                                                                                                                                                                                  
libscalene.cpp:305:65: warning: always_inline function might not be inlinable [-Wattributes]                                                                                                                                                                                      
305 | extern "C" ATTRIBUTE_EXPORT __attribute__((always_inline)) void xxfree_sized(void * ptr, size_t sz) {                                                                                                                                                                         
|                                                                 ^~~~~~~~~~~~                                                                                                                                                                                            
libscalene.cpp:301:65: warning: always_inline function might not be inlinable [-Wattributes]                                                                                                                                                                                      
301 | extern "C" ATTRIBUTE_EXPORT __attribute__((always_inline)) void xxfree(void * ptr) {                                                                                                                                                                                          
|                                                                 ^~~~~~                                                                                                                                                                                                  
libscalene.cpp:295:67: warning: always_inline function might not be inlinable [-Wattributes]
  295 | extern "C" ATTRIBUTE_EXPORT __attribute__((always_inline)) void * xxmalloc(size_t sz) {
      |                                                                   ^~~~~~~~
Heap-Layers/wrappers/gnuwrapper.cpp:66: warning: "CUSTOM_PREFIX" redefined
   66 | #define CUSTOM_PREFIX(x) custom##x
      |
<command-line>: note: this is the location of the previous definition
Heap-Layers/wrappers/wrapper.cpp: In function custommalloc_usable_size:
libscalene.cpp:310:67: error: inlining failed in call to always_inline xxmalloc_usable_size: function body can be overwritten at link time
  310 | extern "C" ATTRIBUTE_EXPORT __attribute__((always_inline)) size_t xxmalloc_usable_size(void * ptr) {
      |                                                                   ^
Heap-Layers/wrappers/wrapper.cpp:238:31: note: called from here
  238 |   return xxmalloc_usable_size (ptr);
      |                               ^
Heap-Layers/wrappers/gnuwrapper-hooks.cpp: In function my_free_hook:
libscalene.cpp:301:65: error: inlining failed in call to always_inline xxfree: function body can be overwritten at link time
  301 | extern "C" ATTRIBUTE_EXPORT __attribute__((always_inline)) void xxfree(void * ptr) {
      |                                                                 ^
Heap-Layers/wrappers/gnuwrapper-hooks.cpp:124:11: note: called from here
  124 |     xxfree(ptr);
      |           ^
```

**Comment by Z4HRA-S** [comment]
Same problem on Ubuntu with python 3.8, but works fine on Fedora. any solution?

**Comment by emeryberger** [comment]
The latest updates should enable a build on `g++` - please take a look!

**Comment by emeryberger** [comment]
Checking in, @boegel @Z4HRA-S

**Comment by hmijail** [comment]
Just installed Scalene 1.1.7 on Amazon Linux 2 on the python 3.8 provided by the Amazon extras, and got the same kind of trouble when trying to profile my script:
> python: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/ec2-user/.local/share/virtualenvs/code_merklization_of_traces-UHx0zGe-/lib/python3.8/site-packages/scalene/libscalene.so)

Other Pypi packages with native code did compile and install correctly, so I guess v1.1.7 still doesn't compile on installation?

It'd be great if you could provide instructions to build and install Scalene from source.

**Comment by emeryberger** [comment]
This should be fixed with https://github.com/emeryberger/scalene/commit/70f2490e651f267e58cafe58f956586acbce4b9a, which I will push momentarily as 1.1.8. The problem was that there was code that was inadvertently relying on a C99 feature.

**Comment by emeryberger** [comment]
Please verify! (Closing the issue)

**Comment by hmijail** [comment]
Uninstalled scalene, reinstalled and got 1.1.8. The problem is still here, only now it requires an even newer version of glibc.

> scalene --version
python: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /home/ec2-user/.local/share/virtualenvs/code_merklization_of_traces-UHx0zGe-/lib/python3.8/site-packages/scalene/libscalene.so)

**Comment by zacqed** [comment]
The issue is persisting with 1.1.8

`python: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /mnt/c/ray/svenv/lib/python3.8/site-packages/scalene/libscalene.so)`

**Comment by emeryberger** [comment]
OK, I just rebuilt this on Amazon Linux 2 (Karoo) and tested it on Ubuntu 20, and it works fine in both places: it's now version 1.1.9. Hopefully this will do the trick...

**Comment by zacqed** [comment]
On WSL, Interesting the same.

```
    Uninstalling scalene-1.1.8:
      Successfully uninstalled scalene-1.1.8
Successfully installed scalene-1.1.9
WARNING: You are using pip version 20.1.1; however, version 20.2.4 is available.
You should consider upgrading via the '/mnt/c/ray/svenv/bin/python -m pip install --upgrade pip' command.
(svenv) harshit@LAPTOP-BIS312A1:/mnt/c/ray$ scalene nnn.py
python: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /mnt/c/ray/svenv/lib/python3.8/site-packages/scalene/libscalene.so)
```

**Comment by emeryberger** [comment]
I just ran this version on WSL2 (Ubuntu 20) with no issues.

**Comment by noklam** [comment]
On Ubuntu 16.04, hitting the same issue

**Comment by artemisart** [comment]
Yes still the same issue on ubuntu 16.04 as well
```
> scalene test_perf.py
python: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/ubuntu/anaconda3/envs/---/lib/python3.8/site-packages/scalene/libscalene.so)
```
I think you should build/keep compatibility with old glibc (or build in the setup.py).

**Comment by emeryberger** [comment]
Right now, the only way that seems like it should work is building on Ubuntu 16.04. I just pushed a new version with such a build: works on Ubuntu 16 & 20, plus WSL2. Hopefully this _finally_ gets the job done.

**Comment by zacqed** [comment]
This is resolved, the profiling is working.

**Comment by artemisart** [comment]
Thanks that works now (I have other unrelated issues but I will post them separately) however I did try to compile with `make CXX=g++` but got this (the first message is an error), should it work with g++ or clang only? @emeryberger 
```
g++ -std=c++14 -g -O3 -DNDEBUG -fno-builtin-malloc -fvisibility=hidden -D'CUSTOM_PREFIX(x)=xx##x' -I/usr/include/nptl -pipe -fPIC -I. -I./include -IHeap-Layers -IHeap-Layers/wrappers -IHeap-Layers/utility -D_REENT
RANT=1 -shared libscalene.cpp Heap-Layers/wrappers/gnuwrapper.cpp -Bsymbolic -o libscalene.so -ldl -lpthread
libscalene.cpp: In function ‘void* xxmemalign(size_t, size_t)’:
libscalene.cpp:118:29: error: ‘class CustomHeapType’ has no member named ‘memalign’
   return getTheCustomHeap().memalign(alignment, sz);
                             ^
In file included from libscalene.cpp:14:0:
./include/memcpysampler.hpp: In member function ‘void MemcpySampler<MemcpySamplingRateBytes>::writeCount() [with long unsigned int MemcpySamplingRateBytes = 2097131ul]’:
./include/memcpysampler.hpp:121:5: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
     write(fd, buf, strlen(buf));
     ^
In file included from libscalene.cpp:13:0:
./include/sampleheap.hpp: In constructor ‘SampleHeap<MallocSamplingRateBytes, SuperHeap>::SampleHeap() [with long unsigned int MallocSamplingRateBytes = 1048549ul; SuperHeap = NextHeap]’:
./include/sampleheap.hpp:64:5: warning: ignoring return value of ‘int ftruncate(int, __off_t)’, declared with attribute warn_unused_result [-Wunused-result]
     ftruncate(_fd, MAX_FILE_SIZE);
     ^
Heap-Layers/wrappers/gnuwrapper.cpp:66:0: warning: "CUSTOM_PREFIX" redefined
 #define CUSTOM_PREFIX(x) custom##x
 ^
<command-line>:0:0: note: this is the location of the previous definition
heaplayers-make.mk:23: recipe for target 'all' failed
make: *** [all] Error 1
```

**Comment by emeryberger** [comment]
This should all be working now; closing.
